name: Push app to production
on:
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.x"
  AZURE_APP_PACKAGE_PATH: "bin/Release/net8.0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: infra/deploy-backend.bicep
          parameters: infra/deployment-parameters.json
          failOnStdErr: false
          scope: "resourcegroup"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and publish
        working-directory: backend/src
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_APP_PACKAGE_PATH }}'

      - name: Deploy backend content
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-florida-man-birthday
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "backend/src/${{ env.AZURE_APP_PACKAGE_PATH }}"

      - name: Deploy static web app content
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
          action: "upload"
          output_location: "dist"
          app_location: "frontend"
